export const useHttpStatus = () => {
    return [
        { "code": 100, "label": "Continue" },
        { "code": 101, "label": "Changement de protocole en cours" },
        { "code": 102, "label": "Traitement en attente (WebDAV ; RFC 2518)" },
        { "code": 103, "label": "Requête interrompue par anticipation (RFC 8297)" },
        { "code": 200, "label": "OK" },
        { "code": 201, "label": "Créé" },
        { "code": 202, "label": "Accepté" },
        { "code": 203, "label": "Informations non autorisées" },
        { "code": 204, "label": "Aucun contenu" },
        { "code": 205, "label": "Réinitialiser le contenu" },
        { "code": 206, "label": "Contenu partiel" },
        { "code": 207, "label": "Statut multi-ressources (WebDAV ; RFC 4918)" },
        { "code": 208, "label": "Déjà signalé (WebDAV ; RFC 5842)" },
        { "code": 226, "label": "IM utilisée (RFC 3229)" },
        { "code": 300, "label": "Choix multiple" },
        { "code": 301, "label": "Déplacé de façon permanente" },
        { "code": 302, "label": "Trouvé" },
        { "code": 303, "label": "Autre" },
        { "code": 304, "label": "Non modifié" },
        { "code": 305, "label": "Utiliser un mandataire" },
        { "code": 307, "label": "Redirection temporaire" },
        { "code": 308, "label": "Redirection permanente" },
        { "code": 400, "label": "Requête incorrecte" },
        { "code": 401, "label": "Non autorisé" },
        { "code": 402, "label": "Paiement requis" },
        { "code": 403, "label": "Interdit" },
        { "code": 404, "label": "Page non trouvée" },
        { "code": 405, "label": "Méthode non autorisée" },
        { "code": 406, "label": "Non acceptable" },
        { "code": 407, "label": "Authentification du mandataire requise" },
        { "code": 408, "label": "Temps d'attente écoulé" },
        { "code": 409, "label": "Conflit" },
        { "code": 410, "label": "Disparu" },
        { "code": 411, "label": "Longueur requise" },
        { "code": 412, "label": "Échec de la condition préalable" },
        { "code": 413, "label": "Entité trop volumineuse" },
        { "code": 414, "label": "URI trop long" },
        { "code": 415, "label": "Type de support non pris en charge" },
        { "code": 416, "label": "Plage de demandes non satisfaisable" },
        { "code": 417, "label": "Attente attendue" },
        { "code": 418, "label": "Je suis une théière" },
        { "code": 421, "label": "Demande dirigée vers un serveur indisponible" },
        { "code": 422, "label": "Entité non traitable (WebDAV ; RFC 4918)" },
        { "code": 423, "label": "Verrouillage verrouillé (WebDAV ; RFC 4918)" },
        { "code": 424, "label": "Échec de la dépendance (WebDAV ; RFC 4918)" },
        { "code": 425, "label": "Trop tôt" },
        { "code": 426, "label": "Mise à niveau requise" },
        { "code": 428, "label": "Précondition requise" },
        { "code": 429, "label": "Trop de demandes" },
        { "code": 431, "label": "Champ d'en-tête de requête trop volumineux" },
        { "code": 451, "label": "Indisponible pour des raisons juridiques" },
        { "code": 500, "label": "Erreur interne du serveur" },
        { "code": 501, "label": "Non implémenté" },
        { "code": 502, "label": "Passerelle incorrecte" },
        { "code": 503, "label": "Service indisponible" },
        { "code": 504, "label": "Temps d'attente de la passerelle écoulé" },
        { "code": 505, "label": "Version HTTP non prise en charge" },
        { "code": 506, "label": "Variant également négociée (RFC 2295)" },
        { "code": 507, "label": "Stockage insuffisant (WebDAV ; RFC 4918)" },
        { "code": 508, "label": "Boucle détectée (WebDAV ; RFC 5842)" },
        { "code": 510, "label": "Non prolongé" },
        { "code": 511, "label": "Authentification réseau requise" }
    ]
}